# This is a basic workflow to help you get started with Actions

name: Run Python Container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
  #  - cron: '5 0 * * *' #runs at 00:05 UTC everyday
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2
        
      # Setups python script
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Runs PIP updade
      - name: Update PIP
        run: python -m pip install --upgrade pip
      
      # Runs requirments install
      - name: Install Requirements
        run: pip install -r requirements.txt # pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Runs a set of commands using the runners shell
      - name: Execute py script # run the run.py to get the latest data
        run: python main.py
        env:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      # Test env vars
#       - name: Hello world
#         run: echo Hello world $USER and $PASS
#         env: 
#           USER: ${{ secrets.USER }}
#           PASS: ${{ secrets.PASS }}
#   build_win:
#     # The type of runner that the job will run on

#     runs-on: windows-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: checkout repo content
#         uses: actions/checkout@v2

#       # Setups python script
#       - name: setup python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}
      
#       # Runs PIP updade
#       - name: Update PIP
#         run: python -m pip install --upgrade pip
      
#       # Runs requirments install
#       - name: Install Requirements
#         run: pip install -r requirements.txt # pip install flake8 pytest
#         #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       # Runs a set of commands using the runners shell
#       - name: Execute py script # run the run.py to get the latest data
#         run: python main.py
#         env:
#           username: ${{ secrets.USER }}
#           password: ${{ secrets.PASS }}
